name: My First Workflow

on:
  push:
  workflow_dispatch:   # manual run button

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello World"

      - name: Show files
        run: ls -la
